Add documentation for EKS
logicalclocks/hops-docs pull request #178
Opened 2020-08-24 11:05 UTC by maismail

2020-08-24 16:13 UTC, berthoug requested changes

2020-08-24 16:13 UTC, berthoug commented on docs/getting_started/hopsworksai/guides/eks_ecr_integration.rst
> +https://us-east-2.console.aws.amazon.com/ec2/v2/home?region=us-east-2#ModifyInboundSecurityGroupRules:securityGroupId=YOUR_EKS_SECURITY_GROUP_ID
you can't click on the link if you need to modify it. I would point to `https://us-east-2.console.aws.amazon.com/ec2/v2/home?region=us-east-2#SecurityGroups:` and then instruct the user to select the security group and to click on `edit inbound rules`

2020-08-24 16:13 UTC, berthoug commented on docs/getting_started/hopsworksai/guides/eks_ecr_integration.rst
> +Choose the region of your EKS cluster, then click Next:
I would put the instruction above the image.

2020-08-24 16:13 UTC, berthoug commented on docs/getting_started/hopsworksai/guides/eks_ecr_integration.rst
> +Choose Enabled to enable the use Amazon EKS and ECR and add your EKS cluster name:
This refers to both the image above and bellow which is confusing. I would separate it in two part and put each part above the corresponding image

2020-08-24 16:13 UTC, berthoug commented on docs/getting_started/hopsworksai/guides/eks_ecr_integration.rst
> +Click Next, choose your SSH Key, click Next and choose the instance profile that you have created in Step 2:
We should probably change the order of the configuration to not have the ssh key in the middle of all of this.

2020-08-24 16:13 UTC, berthoug commented on docs/getting_started/hopsworksai/guides/eks_ecr_integration.rst
> +Click Next, choose the VPC of your EKS cluster:
Maybe add the vpc name format so that people know what to look for.

2020-08-24 16:13 UTC, berthoug commented on docs/getting_started/hopsworksai/guides/eks_ecr_integration.rst
> +Click Next, choose one of the subnets in the VPC:
I would say to select the first or add something to reassure people that it does not matter which one they choose.

2020-08-25 09:14 UTC, berthoug commented on docs/getting_started/hopsworksai/guides/eks_ecr_integration.rst
> +    kubectl edit configmap aws-auth -n kube-system
`KUBE_EDITOR=`

2020-08-26 09:59 UTC, berthoug requested changes
Except for two small corrections, I think it looks good. I would still like if someone else than me could also review it.

2020-08-26 09:59 UTC, berthoug commented on docs/getting_started/hopsworksai/guides/eks_ecr_integration.rst
> +Add your EKS cluster name and update your ECR account id if you want to use another account for ECR, then click Next:
I guess the `ECR account id` is what is called `AWS Account Id` in the picture? If it is the case we should use the same name in both places.

2020-08-26 09:59 UTC, berthoug commented on docs/getting_started/hopsworksai/guides/eks_ecr_integration.rst
> +Choose the securtiy group that you have updated its rules in Step 4, then click Next:
```suggestion
Choose the security group that you have updated in Step 4, then click Next:
```
or rephrase. `that you have updated its rules` does not sound right

2020-08-26 12:57 UTC, kouzant requested changes
You've got our account id scattered in your examples and screenshots. Please randomize it and blur it

2020-08-26 12:57 UTC, kouzant commented on docs/getting_started/hopsworksai/guides/eks_ecr_integration.rst
> +Go to the Roles section of the IAM service in AWS management console by clicking `roles <https://console.aws.amazon.com/iam/home#/roles$new?step=type&roleType=aws&selectedService=EC2&selectedUseCase=
I think there is a logical step here which is not very obvious for the non-tech people. You already mention the steps to click next on Permissions, Tags etc but you don't say that you need to Click on `Create Role`, Select `AWS Service` and `EC2`.

If I don't click on your link I don't know what to do.

2020-08-26 12:57 UTC, kouzant commented on docs/getting_started/hopsworksai/guides/eks_ecr_integration.rst
> +Follow the example below (lines 13-16) to add your role to *mapRoles* and assign *system:masters* group to your role. Make sure to replace 'YOUR ROLE RoleARN' with your role RoleARN before saving.
In the example below it's `YOUR INSTANCE PROFILE ARN` Also, can we make it more bold that it's the `Instance Profile ARN` and not the `Role ARN`

2020-08-26 12:57 UTC, kouzant commented on docs/getting_started/hopsworksai/guides/eks_ecr_integration.rst
> +Follow the example below (lines 13-16) to add your role to *mapRoles* and assign *system:masters* group to your role. Make sure to replace 'YOUR ROLE RoleARN' with your role RoleARN before saving.
Ignore the comment above.

Just make the note below `Warning` I missed it, that's why I wrote the previous comment ;)

2020-08-26 12:57 UTC, kouzant commented on docs/getting_started/hopsworksai/guides/eks_ecr_integration.rst
> +You need to open the HTTP (80) and HTTPS (443) ports on the security group of your eks cluster.
Capitalize `eks`

2020-08-26 12:57 UTC, kouzant commented on docs/getting_started/hopsworksai/guides/eks_ecr_integration.rst
> +First, you need to get the name of the security group of your eks cluster by using the following eksctl command.
You need to say to change the cluster name in the command below

2020-08-26 12:57 UTC, kouzant commented on docs/getting_started/hopsworksai/guides/eks_ecr_integration.rst
> +Once you get the security group id (YOUR_EKS_SECURITY_GROUP_ID), you need to proceed to the AWS management console by clicking `security groups <https://us-east-2.console.aws.amazon.com/ec2/v2/home?r
Capitalize `eks`

2020-08-26 12:57 UTC, kouzant commented on docs/getting_started/hopsworksai/guides/eks_ecr_integration.rst
> +Step 5: Create a hopsworks cluster with EKS and ECR support
Capitalize first letter in `hopsworks`

2020-08-26 12:57 UTC, kouzant commented on docs/getting_started/hopsworksai/guides/eks_ecr_integration.rst
> +Choose the security group that you have updated in Step 4, then click Next:
EKS creates three Security Groups and step 4 is far behind especially if you follow the instructions for the first time. Can you say something like Select the Security Group in the form of `eks-cluster-sg-CLUSTER-NAME` and **NOT** the ones for `ControlPlaneSecurity` or `ClusterSharedNode`. Or something similar ;) It's easy to mess it up here

2020-08-27 09:20 UTC, berthoug approved these changes

2020-08-27 09:26 UTC, kouzant approved these changes

2020-08-27 09:28 UTC, merged