[HOPSWORKS-1702] register user as admin
logicalclocks/hops-docs pull request #179
Opened 2020-08-28 15:14 UTC by ErmiasG

2020-08-28 15:56 UTC, tkakantousis requested changes

2020-08-28 15:56 UTC, tkakantousis commented on docs/admin_guide/user-administration.rst
> +To find this id in Active directory go to users and computers management window and right click on the user you want to
```suggestion
To find this id in Active directory go to "users and computers" management window and right click on the user you want to
```

2020-08-28 15:56 UTC, tkakantousis commented on docs/admin_guide/user-administration.rst
> +To find the uuid in LDAP run 'ldapsearch' as shown in the image below.
```suggestion
To find the `UUID` in LDAP run 'ldapsearch' as shown in the image below.
```

2020-08-28 15:56 UTC, tkakantousis commented on docs/admin_guide/user-administration.rst
> +To register a remote user you need a 'UUID' that is the universally unique id of the remote user in LDAP or Kerberos.
```suggestion
To register a remote user you need a `UUID` that is the universally unique id of the remote user in LDAP or Kerberos.
```

2020-08-31 08:14 UTC, ErmiasG commented
logicalclocks/hops-testing-ee/pull/158

2020-08-31 14:08 UTC, tkakantousis approved these changes

2020-09-03 14:07 UTC, merged